services:
  discovery-service:
    container_name: discovery-service
    image: ouday2025/discovery-service:latest
    build:
      context: ./eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    hostname: eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  mysql-container:
    container_name: mysql-container-offre
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=OffrePromotion
    ports:
      - "3306:3306"
    depends_on:
      - discovery-service
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  gateway-service:
    container_name: gateway-service
    image: ouday2025/gateway-service:latest
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    ports:
      - "8093:8093"
    hostname: gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - app-network

  offre-promotion-service:
    container_name: offre-promotion-service
    image: ouday2025/offre-promotion-service:latest
    build:
      context: ./offre_promotion
      dockerfile: Dockerfile
    ports:
      - "8085:8088"
    hostname: offre-promotion
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container-offre:3306/OffrePromotion?autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
      mysql-container:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge